import { createApp } from "vue";
import App from "./App.vue";
import routes from "./router/index";
import registerComponent from "./config";
import "@vueup/vue-quill/dist/vue-quill.snow.css";
import pinia from "@/store/pinia";
import echarts from "@/config/echarts";
const app = createApp(App);
app.use(pinia);
registerComponent(app);
app.config.globalProperties.$charts = echarts;
app.use(routes).mount("#app");
